##
# Architecture 01  
##
arch01:
  enabled: true
  name: arch01
  namespaces:
    arch01-test1: {}
    arch01-test2: {}
    arch01-test3: {}

##
# Architecture 02
##
arch02:
  enabled: true
  name: arch02
  argocd_instance: argocd
  argocd_namespace: gitops-arch02
  namespaces:
    arch02-test1:
      quotas:
          hard:
            configmaps: 30
    arch02-test2: {}
    arch02-test3: {}
  argocd_quotas:
    hard:
      count/application.argoproj.io: 15
  default_quotas:
    hard:
      limits.cpu: "6" 
      limits.memory: 254Gi 
      limits.ephemeral-storage: 42Gi
  argoproj_extra_roles:
    - name: arch02-developers
      description: Read and Sync permissions for operators
      policies:
        - p, role:developer-dev, applications, get, dev/*, allow
        - p, role:developer-dev, applications, sync, dev/*, allow
      groups:
      - arch02-developers
  chart_repos: 
    - "https://github.com/acidonper*"
  objs_allowed:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: 'route.openshift.io'
      kind: Route

##
# Architecture 03
##
# arch03:
#   enabled: true
#   name: arch03
#   namespaces:
#     arch03-test1: {}
#     arch03-test2: {}
#     arch03-test3: {}