# Arch Operation Chart Default Values
name: arch01

namespaces: {} 

argocd_infra_ns: openshift-gitops
argocd_instance: argocd
argocd_namespace: argocd

argocd_quotas:
  hard:
    count/application.argoproj.io: 10

chart_repos: []

objs_allowed:
  - group: '*'
    kind: '*'

default_quotas:
  hard:
    requests.cpu: "1" 
    requests.memory: 1Gi 
    requests.ephemeral-storage: 2Gi 
    limits.cpu: "2" 
    limits.memory: 2Gi 
    limits.ephemeral-storage: 4Gi
    pods: 4
    configmaps: 10
    persistentvolumeclaims: 4
    replicationcontrollers: 20
    secrets: 10
    services: 10

global_labels: 
  test.labels.io/testing: test_label

global_annotations:
  test.annotations.io/testing: test_annotation