{{- range $key, $val := $.Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $key }}
  labels:
    argocd.argoproj.io/managed-by: {{ $argocd_infra_ns }}
  {{- with $.Values.global_labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $.Values.global_annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}