{{- range $ns := $.Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
  {{- with $.Values.global_labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $.Values.global_annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}