{{- range $key, $val := $.Values.namespaces }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quotas
  namespace: {{ $key }}
spec:
{{- if $val.quotas }}
  {{- with $newdict := merge $val.quotas $.Values.default_quotas }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- else }}
  {{- with $.Values.default_quotas }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
---
{{- end }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quotas
  namespace: {{ $.Values.argocd_namespace }}
spec:
  {{- with $.Values.argocd_quotas }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
---