{{- range $ns := $.Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller
  namespace: {{ $ns }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:{{ $.Values.argocd_namespace }}:{{ $.Values.argocd_instance }}-argocd-application-controller'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
{{- end }}